### ISSUE TITLE
DiffStrategy

### ISSUE THREAD

**Issue by AbbyANoble** [StevenClontz/checkit-calculus#3]
<img width="1057" alt="Screen Shot 2021-08-16 at 10 41 43 PM" src="https://user-images.githubusercontent.com/85640990/129655667-0c8a7499-b572-4803-9dd7-5f3c20170c10.png">
<img width="1079" alt="Screen Shot 2021-08-16 at 10 41 27 PM" src="https://user-images.githubusercontent.com/85640990/129655669-bf4b1ca4-4f40-42bd-a386-a46dff3bd5a9.png">

Prevent power rule problems from showing up in this section as shown in part (a) of the attachments.

**Comment by StevenClontz** [comment]
Thanks for the report @AbbyANoble! Looks like we're fixed at https://stevenclontz.github.io/checkit-calculus/#/bank/DiffStrategy
